target 'JJImagePickerDemo' do

	pod 'AFNetwork'
	pod 'UITextView+Placeholder'
	pod 'SVProgressHUD'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'YYText'
    pod 'Qiniu', "~> 7.1"
    pod 'MJRefresh'
    
end
